name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install Qt
      uses: jurplel/install-qt-action@v4.1.1
      with:
        host: mac
        target: desktop

    - name: Build Desktop App
      run: |
        ./Users/runner/work/DollyXs/Qt/5.15.2/clang_64/bin/qmake
        make
