name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install Qt
      uses: jurplel/install-qt-action@v4.1.1
      with:
        host: mac
        target: desktop
        version: 6.0.4
        

    - name: Build Desktop App
      run: |
        qmake -config release
        make
    - name: Echo Output
      run: ls -all

    - name: Deploy QT App
      if: always      
      run: macdeployqt DollyX.app -dmg

    - name: Download a Build Artifact
      if: always
      uses: actions/download-artifact@v4.2.1
      with:
        name: DollyX.dmg
