name: C/C++ CI

on:
  push:
    branches: [ "main" ] 
  pull_request:
    types: [closed]
    branches: [ "main"]
    
  workflow_dispatch:
    inputs:
      environment:
        description: 'Hangi ortamda çalıştırmak istiyorsunuz?'
        type: choice
        options:
        - development
        - staging
        - production
        required: true
      tag_name:
        description: 'Release için tag adı'
        type: string
        required: false

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install Qt
      uses: jurplel/install-qt-action@v4.1.1
      with:
        host: mac
        target: desktop
        version: 6.0.4
        

    - name: Build Desktop App
      run: |
        qmake -config release
        make
        macdeployqt DollyXs.app -dmg


    - name: Find DMG File
      id: find_dmg
      run: |
        find . -name "DollyXs.dmg" -print0 | while IFS= read -r -d $'\0' file; do
          echo "::set-output name=dmg_path::$file"
        done

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }} 
      with:
        tag_name: ${{ github.run_number }} 
        release_name: Release ${{ github.run_number }}
        draft: false
        prerelease: false

    - name: Upload Release Asset
      id: upload-release-asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ${{ steps.find_dmg.outputs.dmg_path }} 
        asset_name: DollyXs.dmg
        asset_content_type: application/octet-stream
