name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install Qt
      uses: jurplel/install-qt-action@v4.1.1
      with:
        version: 6.2.8
        host: mac
        target: desktop

    - name: Build Desktop App
      run: |
        qmake
        make
    
